# -*- coding: utf-8 -*-
"""Copy of sentence classifier_api.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xJEUGf7N2EymbYqX_yKtV0ob4S5MZbwi
"""

!pip install flask-ngrok

from keras.preprocessing.text import Tokenizer
from keras.preprocessing import sequence
from keras.models import load_model

from flask_ngrok import run_with_ngrok
from flask import Flask, request, redirect, url_for, flash, jsonify
from flask import request
import numpy as np

app = Flask(__name__)
run_with_ngrok(app)

modelfile = '/content/model_74.h5'
model = load_model(modelfile)

@app.route('/predict', methods=['GET', 'POST'])
def predict():
    if request.method == 'POST':
      message = request.form['message']
      sample_text = [message]
      sample_sequence = tok.texts_to_sequences(sample_text)
      sample_sequence_matrix = sequence.pad_sequences(sample_sequence, maxlen=max_len)
      my_prediction = np.array2string(model.predict(sample_sequence_matrix))
      return render_template('result.html',prediction = my_prediction.round())

if __name__ == '__main__':
    app.run()

